
package com.xubao.test.simpleTest.webService.remote;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RpcTestService", targetNamespace = "http://webService.simpleTest.test.xubao.com/", wsdlLocation = "http://192.168.1.52:9002/rpcTest?wsdl")
public class RpcTestService
    extends Service
{

    private final static URL RPCTESTSERVICE_WSDL_LOCATION;
    private final static WebServiceException RPCTESTSERVICE_EXCEPTION;
    private final static QName RPCTESTSERVICE_QNAME = new QName("http://webService.simpleTest.test.xubao.com/", "RpcTestService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.52:9002/rpcTest?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RPCTESTSERVICE_WSDL_LOCATION = url;
        RPCTESTSERVICE_EXCEPTION = e;
    }

    public RpcTestService() {
        super(__getWsdlLocation(), RPCTESTSERVICE_QNAME);
    }

    public RpcTestService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RPCTESTSERVICE_QNAME, features);
    }

    public RpcTestService(URL wsdlLocation) {
        super(wsdlLocation, RPCTESTSERVICE_QNAME);
    }

    public RpcTestService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RPCTESTSERVICE_QNAME, features);
    }

    public RpcTestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RpcTestService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RpcTest
     */
    @WebEndpoint(name = "RpcTestPort")
    public RpcTest getRpcTestPort() {
        return super.getPort(new QName("http://webService.simpleTest.test.xubao.com/", "RpcTestPort"), RpcTest.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RpcTest
     */
    @WebEndpoint(name = "RpcTestPort")
    public RpcTest getRpcTestPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webService.simpleTest.test.xubao.com/", "RpcTestPort"), RpcTest.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RPCTESTSERVICE_EXCEPTION!= null) {
            throw RPCTESTSERVICE_EXCEPTION;
        }
        return RPCTESTSERVICE_WSDL_LOCATION;
    }

}
