/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xubao_test_simpleTest_jniTest_JniTest */

#ifndef _Included_com_xubao_test_simpleTest_jniTest_JniTest
#define _Included_com_xubao_test_simpleTest_jniTest_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xubao_test_simpleTest_jniTest_JniTest
 * Method:    echo
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xubao_test_simpleTest_jniTest_JniTest_echo
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
